#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'designerPdfViewer' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY h
#  2. STRING word
#

def designerPdfViewer(h, word):
    # Write your code here

    alphabet_index = "abcdefghijklmnopqrstuvwxyz"
    alphabet_list = list(alphabet_index)
    max_value = 1
    for character in word:
        index_value = alphabet_list.index(character)
        print(index_value)
        if h[index_value] > max_value:
            max_value = h[index_value]
    
    area = len(word) * max_value
    return area
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
